--Question 4
SELECT W.LASTNAME || ' ' || W.FIRSTNAME AS FULL_NAME FROM WORKER W
INNER JOIN ASSIGN A
ON W.EMPID = A.EMPID 
INNER JOIN PROJECT P 
ON A.PROJNO = P.PROJNO 
WHERE P.PROJNO = '1040'
ORDER BY W.LASTNAME;


