--Question 7
SELECT W.LASTNAME || ' ' || W.FIRSTNAME AS FULL_NAME, D.DEPARTMENTNAME FROM WORKER W
INNER JOIN DEPT D
ON D.DEPARTMENTID = W.DEPARTMENTID
WHERE W.EMPID IN (SELECT EMPID FROM ASSIGN
WHERE PROJNO = 1019);




