--Question 8
SELECT W.FIRSTNAME, W.LASTNAME, A.RATING
FROM WORKER W
INNER JOIN ASSIGN A
ON W.EMPID = A.EMPID
INNER JOIN PROJECT P
ON A.PROJNO = P.PROJNO
WHERE P.PROJMGRID = (SELECT EMPID FROM WORKER
WHERE LASTNAME = 'Liu' AND FIRSTNAME = 'Jun-Min')
ORDER BY W.LASTNAME;





